pipeline{
    agent any
    environment{
        MAVEN_PROJ_DIR = 'java'
    }
    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }
        stage('Validate'){
           steps{
                dir(env.MAVEN_PROJ_DIR){
                    sh 'mvn validate'
                }   
            }
        }
        
        stage('Test'){
            steps{
                dir(env.MAVEN_PROJ_DIR){
                    sh 'mvn test'
                }   
            }
        }
    }
}
