pipeline{
    agent any
    environment{
        MAVEN_PROJ_DIR = 'java'
    }
    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }
        stage('Validate'){
           steps{
                dir(env.MAVEN_PROJ_DIR){
                    sh 'mvn validate'
                }   
            }
        }
        stage('Test'){
            steps{
                dir(env.MAVEN_PROJ_DIR){
                    sh 'mvn test'
                }   
            }
        }
        stage('Sonarqube Analysis'){
            steps{
                dir(env.MAVEN_PROJ_DIR){
                    withCredentials([string(credentialsID: 'test-sonarqube-id', variable: 'SONAR_TOKEN')]){
                        echo "SonarQube Token: $SONAR_TOKEN"
                       sh ''' 
                            mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                            -Dsonar.projectKey=jenkins-sonarqube \
                            -Dsonar.projectName='jenkins-sonarqube' \
                            -Dsonar.host.url=http://sonarqube:9000 \
                            -Dsonar.token=$SONAR_TOKEN \
                            -Dsonar..scanner.skipJreProvisioning=true
                       '''
            }
        }
    }
}
    }
}
